
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SunTest.Orm
{

using System;
    using System.Collections.Generic;
    
public partial class Crew
{

    public string CrewID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Airline { get; set; }

    public string Airport { get; set; }

    public string Title { get; set; }

    public Nullable<int> StartDate { get; set; }

    public Nullable<int> EndDate { get; set; }

}

}
