
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SunTest.Orm
{

using System;
    using System.Collections.Generic;
    
public partial class FlightScheduleCrew
{

    public int FlightScheduleCrewID { get; set; }

    public string CrewID { get; set; }

    public Nullable<int> FlightScheduleID { get; set; }

}

}
