
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SunTest.Orm
{

using System;
    using System.Collections.Generic;
    
public partial class FlightScheduleDayOfWeek
{

    public int DayID { get; set; }

    public string WeekDay { get; set; }

    public Nullable<bool> IsSchedule { get; set; }

    public string Currency { get; set; }

    public Nullable<int> SpendPerHead { get; set; }

    public Nullable<int> IncentiveTarget { get; set; }

    public int FlightScheduleID { get; set; }

}

}
