

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SunTest.Orm
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class SunExpressEntities : DbContext
{
    public SunExpressEntities()
        : base("name=SunExpressEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<ApiUsers> ApiUsers { get; set; }

    public virtual DbSet<Crew> Crew { get; set; }

    public virtual DbSet<FlightSchedule> FlightSchedule { get; set; }

    public virtual DbSet<PostFlight> PostFlight { get; set; }

    public virtual DbSet<PostFlightCrew> PostFlightCrew { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<FlightScheduleCrew> FlightScheduleCrew { get; set; }

    public virtual DbSet<FlightScheduleDayOfWeek> FlightScheduleDayOfWeek { get; set; }

}

}

